# Generated by Django 3.0.6 on 2020-06-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='casvstavani',
            field=models.TimeField(),
        ),
    ]
