# Generated by Django 3.0.6 on 2020-06-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200620_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='OSpocitace',
        ),
        migrations.AddField(
            model_name='data',
            name='SpokojenySeSkolnimSys',
            field=models.CharField(default='Ano', max_length=10),
        ),
    ]
