# Generated by Django 3.0.6 on 2020-06-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_graphs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graphs',
            new_name='Graph',
        ),
    ]
