# Generated by Django 3.0.6 on 2020-06-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200628_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo', models.CharField(max_length=100000)),
            ],
            options={
                'verbose_name_plural': 'graphs',
            },
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
    ]
