# Generated by Django 3.0.6 on 2020-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200628_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphs',
            old_name='demo',
            new_name='vysky_cary',
        ),
        migrations.AddField(
            model_name='graphs',
            name='vysky_hist',
            field=models.CharField(default='default', max_length=100000),
        ),
    ]
