# Generated by Django 3.0.6 on 2020-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200628_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='delky_spanku',
            field=models.CharField(default='default', max_length=100000),
        ),
    ]
