# Generated by Django 3.0.6 on 2020-07-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_graphs_delky_spanku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphs',
            old_name='delky_spanku',
            new_name='delky_spanku_hist',
        ),
    ]
