# Generated by Django 3.0.6 on 2020-07-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200702_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphs',
            old_name='vysky_cary',
            new_name='vysky_graph',
        ),
        migrations.AddField(
            model_name='graphs',
            name='delky_spanku_graph',
            field=models.CharField(default='default', max_length=100000),
        ),
    ]
