# Generated by Django 3.0.6 on 2020-07-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200702_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='pohlavi_kolac',
            field=models.CharField(default='default', max_length=100000),
        ),
    ]
