# Generated by Django 3.0.6 on 2020-07-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_graphs_pohlavi_kolac'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='typy_mobilu_kolac',
            field=models.CharField(default='default', max_length=100000),
        ),
    ]
