# Generated by Django 3.0.6 on 2020-07-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_graphs_typy_mobilu_kolac'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='vysky_hist_muzi',
            field=models.CharField(default='default', max_length=100000),
        ),
        migrations.AddField(
            model_name='graphs',
            name='vysky_hist_zeny',
            field=models.CharField(default='default', max_length=100000),
        ),
    ]
