# Generated by Django 3.0.6 on 2020-07-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200721_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphs',
            old_name='vysky_graph_muzi',
            new_name='vysky_graph_muzi_a_zeny',
        ),
        migrations.RemoveField(
            model_name='graphs',
            name='vysky_graph_zeny',
        ),
    ]
