# Generated by Django 3.0.6 on 2020-07-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200721_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='delky_spanku_graph_muzi_a_zeny',
            field=models.CharField(default='default', max_length=100000),
        ),
        migrations.AddField(
            model_name='graphs',
            name='delky_spanku_hist_muzi',
            field=models.CharField(default='default', max_length=100000),
        ),
        migrations.AddField(
            model_name='graphs',
            name='delky_spanku_hist_zeny',
            field=models.CharField(default='default', max_length=100000),
        ),
    ]
