# Generated by Django 3.0.6 on 2020-07-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200721_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='pohlavi_hist',
            field=models.CharField(default='default', max_length=100000),
        ),
    ]
