# Generated by Django 3.0.6 on 2020-07-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_graphs_pohlavi_hist'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='cas_na_soc_hist',
            field=models.CharField(default='default', max_length=100000),
        ),
        migrations.AddField(
            model_name='graphs',
            name='cas_na_soc_hist_muzi',
            field=models.CharField(default='default', max_length=100000),
        ),
        migrations.AddField(
            model_name='graphs',
            name='cas_na_soc_hist_zeny',
            field=models.CharField(default='default', max_length=100000),
        ),
    ]
