# Generated by Django 3.0.6 on 2020-07-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200727_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='cas_na_soc_graph',
            field=models.CharField(default='default', max_length=100000),
        ),
        migrations.AddField(
            model_name='graphs',
            name='cas_na_soc_graph_muzi_a_zeny',
            field=models.CharField(default='default', max_length=100000),
        ),
    ]
