# Generated by Django 3.1 on 2020-08-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_graphs_typy_mobilu_hist'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='cas_vstavani_graph',
            field=models.CharField(default='default', max_length=100000),
        ),
        migrations.AddField(
            model_name='graphs',
            name='cas_vstavani_graph_muzi',
            field=models.CharField(default='default', max_length=100000),
        ),
        migrations.AddField(
            model_name='graphs',
            name='cas_vstavani_graph_zeny',
            field=models.CharField(default='default', max_length=100000),
        ),
        migrations.AddField(
            model_name='graphs',
            name='cas_vstavani_hist',
            field=models.CharField(default='default', max_length=100000),
        ),
        migrations.AddField(
            model_name='graphs',
            name='cas_vstavani_hist_muzi',
            field=models.CharField(default='default', max_length=100000),
        ),
        migrations.AddField(
            model_name='graphs',
            name='cas_vstavani_hist_zeny',
            field=models.CharField(default='default', max_length=100000),
        ),
    ]
