# Generated by Django 3.1 on 2020-08-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20200818_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphs',
            old_name='cas_vstavani_graph_muzi',
            new_name='cas_vstavani_graph_muzi_a_zeny',
        ),
        migrations.RemoveField(
            model_name='graphs',
            name='cas_vstavani_graph_zeny',
        ),
    ]
